### ISSUE TITLE
NetBoxInventory2 Platform normalization

### ISSUE THREAD

**Issue by egreenspan2** [wvandeun/nornir_netbox#12]
NetBoxInventory2 plugin seems to default to "name" as the "platform" field when retrieving data from NB.

Are there any objections to PR to use similar init boolean to "use_slugs" similar to NBInventory class?
```python
use_slugs: bool = True
```

**Comment by wvandeun** [comment]
No objections, I would suggest to name the argument `use_platform_slug`. `use_slugs` doesn't make sense anymore since we would only do it for 1 specific attribute and not for multiple.
