### ISSUE TITLE
Give the ability to use Napalm driver as the platform rather than the actual platform name or slug

### ISSUE THREAD

**Issue by melkypie** [wvandeun/nornir_netbox#22]
Currently if you want to integrate with the nornir_napalm plugin which seems to look at platform in host, you cannot have a differently named name or slug than the actual Napalm driver.

Seems like this will require another request be made to the Netbox API as the Napalm driver info is not passed in the devices endpoint (correct me if I'm wrong).

**Comment by wvandeun** [comment]
Hi,
What you are describing is indeed the intended behaviour, which is exactly the same behaviour as the Ansible NetBox inventory plugin (AFAIK).
Just out of curiosity, how are you defining the platform in NetBox?

Technically it is possible what you are describing. It would require an additional API call to retrieve all the platforms and then extract the napalm driver.

**Comment by melkypie** [comment]
Currently platform has manufacturer with the system name, ex., Arista Eos.
If there could be an option that would just replace use_platform_slug with something like platform_field, that would have name, slug or driver options with name of course being the default, would be great.
I could probably manage to do this myself if no one finds the time.

**Comment by tyler-8** [comment]
One possibility I could see is retrieving the full list of platforms alongside the devices/VMs - that way you're only incurring a single (or several depending on platform count) additional API call, rather than one call for all devices.

**Comment by NetIgo** [comment]
+ 1

I run into a similar situation this week.
I wanted to use a specific platform 'cisco_xe'.
But as you can imagine if i update the platform name or slug with 'cisco_xe', i won't be able to use the nornir_naplam anymore.
This is why i think it's a good idea.
