### ISSUE TITLE
filter parameter as list of dictionaries

### ISSUE THREAD

**Issue by sjtarik** [wvandeun/nornir_netbox#23]
I want to filter devices on multiple tags but if I pass filter_parameters as a dictionary, single key like "tag" would only pass a single value. Do you think is there a way to pass multiple tags as request parameters using nornir_netbox similar to this [Netbox documentation example](https://netbox.readthedocs.io/en/stable/models/extras/tag/)?

`GET /api/dcim/devices/?tag=monitored&tag=deprecated`

**Comment by wvandeun** [comment]
https://nornir-netbox.readthedocs.io/en/latest/usage/#configuration-options
see section on filter_parameters

you can filter multiple values for a single parameter (logical OR) using a list.
```python
filter_parameters: { "tags": [ "tag_1", "tag_2"] }
```

**Comment by sjtarik** [comment]
thank you so much @wvandeun. your help is always timely and on point, appreciated.
