### ISSUE TITLE
Poetry Dependencies Nornir 3.1.0

### ISSUE THREAD

**Issue by NetIgo** [wvandeun/nornir_netbox#25]
Hello,

First of, thanks for your work, it does really help to have Netbox as an Inventory instead of the Simpleinventory.

Nornir 3.1.0 was release 3 days ago, and it seems that there is a version dependencies for nornir in the poetry configuration.
So, when you install nornir-netbox, nornir 3.1.0 get uninstall and replace by 3.0.0.

Maybe we could update the dependencies files ?

Thanks

**Comment by wvandeun** [comment]
Should have been  fixed in develop branch, can you test installing from there?
`pip install git+https://github.com/wvandeun/nornir_netbox.git@develop`

**Comment by NetIgo** [comment]
It works.
Thanks for your reactivity
So when we simply pip3 install nornir-netbox, which branch is use ? master ?
