### ISSUE TITLE
incorrect platform being set

### ISSUE THREAD

**Issue by lachlan748** [wvandeun/nornir_netbox#29]
NetBoxInventory2 seems to be assuming that the 'platform' for a particular node equals the NAPALM driver name, which in my case, is incorrect. I use platform names such as eos-4.20.x, eos-4.23.x, ios-15.x.x, nxos-7.x.x etc.

Can line 146 be modified in your code to pull platform data from device['platform']['napalm_driver'] rather than device['platform']['name']?

Note: I'm using Netbox v2.9.8.

**Comment by wvandeun** [comment]
Platform name cannot be used, you can use the slug as an alternative.
https://nornir-netbox.readthedocs.io/en/latest/usage/#use-platform-slugs

**Comment by lachlan748** [comment]
Thanks for the prompt response. I followed your suggestion but still hit a problem. Let me explain. 

In NetBox, I have a platform with name 'NXOS-7.0(3)I7(8)' with a slug name nxos-7-03i78, but the napalm_driver is set correctly as 'nxos'. Netbox can successfully pull LLDP and config data from the node.

Using nornir_netbox, when setting 'use_platform_napalm_driver' as True, I get platform 'NXOS-7.0(3)I7(8)'. Nornir then fails to pull data from the device.

If I swap to 'use_platform_slug' as True, I get platform 'nxos-7-03i78', again Nornir fails to connect.

Ideally, I want to set 'use_platform_napalm_driver' as True, as per line 276 in your code, but since 281/282 doesn't apply (my platform slug doesn't match the napalm driver name), line 283 catches me, and then incorrectly sets the platform to the platform name.

So effectively, use_platform_napalm_driver doesn't seem to work as intended. Can this be fixed?

**Comment by wvandeun** [comment]
Sorry for the late response, but you have to install from the development branch to use `use_platform_napalm_driver`.
I'll publish a new release to pypi this week.
